// <auto-generated />
namespace TurkSeker.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addEregliScadaTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addEregliScadaTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202101132035124_addEregliScadaTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
